version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: tuhedb
      MYSQL_ROOT_PASSWORD: dodik2000
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  web:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tuhedb?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dodik2000
    ports:
      - "8087:8087"
    depends_on:
      - db

volumes:
  db-data: